apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= # Just an example base64 encoded
  mongo-root-password: cGFzc3dvcmQ= # Just an example base64 encoded
